### PR TITLE
Retire kernel 3.2 and 3.4?

### PR DESCRIPTION
**Pull request by ninaholic**
These have never really worked for me in newest kernel-kit. The error is always about /fs/aufs. Now that 3.2 is EOL, maybe it's time to retire them?

3.2.102

```
  CC      fs/aufs/module.o
  CC      fs/aufs/sbinfo.o
  CC      fs/aufs/super.o
  CC      fs/aufs/branch.o
  CC      fs/aufs/xino.o
  CC      fs/aufs/sysaufs.o
  CC      fs/aufs/opts.o
  CC      fs/aufs/wkq.o
  CC      fs/aufs/vfsub.o
  CC      fs/aufs/dcsub.o
fs/aufs/dcsub.c: In function ‘au_dcsub_pages’:
fs/aufs/dcsub.c:136:27: error: ‘union <anonymous>’ has no member named ‘d_child’
fs/aufs/dcsub.c:136:27: warning: initialization from incompatible pointer type [enabled by default]
fs/aufs/dcsub.c:136:27: warning: (near initialization for ‘dentry’) [enabled by default]
fs/aufs/dcsub.c:136:27: error: ‘union <anonymous>’ has no member named ‘d_child’
fs/aufs/dcsub.c:173:20: error: ‘union <anonymous>’ has no member named ‘d_child’
make[2]: *** [fs/aufs/dcsub.o] Error 1
make[1]: *** [fs/aufs] Error 2
make: *** [fs] Error 2
Error: failed to compile the kernel sources.
```

3.2.87

```
  CC      fs/aufs/module.o
  CC      fs/aufs/sbinfo.o
  CC      fs/aufs/super.o
  CC      fs/aufs/branch.o
  CC      fs/aufs/xino.o
  CC      fs/aufs/sysaufs.o
  CC      fs/aufs/opts.o
  CC      fs/aufs/wkq.o
  CC      fs/aufs/vfsub.o
  CC      fs/aufs/dcsub.o
fs/aufs/dcsub.c: In function ‘au_dcsub_pages’:
fs/aufs/dcsub.c:136:27: error: ‘union <anonymous>’ has no member named ‘d_child’
fs/aufs/dcsub.c:136:27: warning: initialization from incompatible pointer type [enabled by default]
fs/aufs/dcsub.c:136:27: warning: (near initialization for ‘dentry’) [enabled by default]
fs/aufs/dcsub.c:136:27: error: ‘union <anonymous>’ has no member named ‘d_child’
fs/aufs/dcsub.c:173:20: error: ‘union <anonymous>’ has no member named ‘d_child’
make[2]: *** [fs/aufs/dcsub.o] Error 1
make[1]: *** [fs/aufs] Error 2
make: *** [fs] Error 2
Error: failed to compile the kernel sources.
```

3.4.113

```
  CC      fs/aufs/module.o
  CC      fs/aufs/sbinfo.o
  CC      fs/aufs/super.o
  CC      fs/aufs/branch.o
fs/aufs/branch.c: In function ‘au_farray_cb’:
fs/aufs/branch.c:1006:2: error: ‘struct super_block’ has no member named ‘s_files’
fs/aufs/branch.c:1006:2: error: ‘struct super_block’ has no member named ‘s_files’
fs/aufs/branch.c:1006:2: error: ‘struct super_block’ has no member named ‘s_files’
fs/aufs/branch.c:1006:2: error: ‘struct super_block’ has no member named ‘s_files’
fs/aufs/branch.c:1006:2: error: ‘struct super_block’ has no member named ‘s_files’
fs/aufs/branch.c:1006:2: error: ‘union <anonymous>’ has no member named ‘fu_list’
fs/aufs/branch.c:1006:2: warning: initialization from incompatible pointer type [enabled by default]
fs/aufs/branch.c:1006:2: error: ‘union <anonymous>’ has no member named ‘fu_list’
fs/aufs/branch.c:1006:2: error: ‘union <anonymous>’ has no member named ‘fu_list’
fs/aufs/branch.c:1006:2: error: ‘union <anonymous>’ has no member named ‘fu_list’
fs/aufs/branch.c:1006:2: error: ‘union <anonymous>’ has no member named ‘fu_list’
fs/aufs/branch.c:1006:2: error: ‘union <anonymous>’ has no member named ‘fu_list’
make[2]: *** [fs/aufs/branch.o] Error 1
make[1]: *** [fs/aufs] Error 2
make: *** [fs] Error 2
Error: failed to compile the kernel sources.
```

### CODE REVIEW

**Comment by ninaholic** [comment]
I read this commit might fix the error in 3.2 (introduced in 3.2.66). Now to test

https://github.com/sfjro/aufs3-linux/commit/30d345d
https://sourceforge.net/p/aufs/mailman/message/33297752/

**Comment by wdlkmpx** [comment]
I think both kernel configs can be removed. Really old and obsolete hardware works fine with k3.14 or even kernel 4.1, of course support for some legacy stuff was removed, but it can be overlooked.

Last year i tested a nvidia card made in 1999 with dpup, i watched some 720p videos, no propietary drivers needed. It was not possible to achieve that in precise puppy without the propietary driver.

I see you posted a patch for k3.2. So at least the k3.4 config can be safely removed. But you might want to confirm kernel k3.2.112 compiles and runs before any action is taken..

**Comment by ninaholic** [comment]
Hi wdlxmpx!

I have always used 3.14 on old hardware too and found that more things worked better in it than in earlier kernels, and it was stable. It's also the lowest that was used in Puppy 6.x (Tahrpup, Slacko) it seems.

The 3.2 kernel did compile with the patch, but when I booted with it, one laptop (Pentium M) got stuck on "Setting up (networking" and didn't make it to desktop, and the other (Core2Duo) did slowly show the desktop after a 5-10 second delay of black screen but did not see my b43 wireless (even though the firmware was there), so I think maybe it's not good idea to use 3.2 any longer either for the reasons you mentioned. Here's the kernel it made though if you are masochist https://files.fm/u/j3wbgnpd :laughing:

**Comment by wdlkmpx** [comment]
I'm using dpup with kernel 3.2.102, well unlike k3.4 i don't srr graphical glitches that render fonts unreadable. I see you closed the other pull request.. i'm having doubts... but i guess i'll merge this anyway

**Comment by ninaholic** [comment]
@wdlkmpx you can open and merge the 3.2 patch if you think it's still useful, at least it compiles now :smile: I was torn on which direction to pick too for it...
