### ISSUE TITLE
/kernel-kit/patches/commoncap-symbol.patch fails in k4.14

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1102]
/kernel-kit/patches/commoncap-symbol.patch
does not work in kernel 4.14.....
build error=
```
security/commoncap.c:844:15: error: ‘cap_bprm_secureexec’ undeclared here (not in a function)
 EXPORT_SYMBOL(cap_bprm_secureexec);
               ^
./include/linux/export.h:65:16: note: in definition of macro ‘___EXPORT_SYMBOL’
  extern typeof(sym) sym;      \
                ^
security/commoncap.c:844:1: note: in expansion of macro ‘EXPORT_SYMBOL’
 EXPORT_SYMBOL(cap_bprm_secureexec);
 ^
scripts/Makefile.build:314: recipe for target 'security/commoncap.o' failed
make[1]: *** [security/commoncap.o] Error 1
```

**Comment by mavrothal** [comment]
This function has been removed in 4.14 kernel (I guess all executions are secured now).
I guess build.sh should be modified (around [Line 583](https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/kernel-kit/build.sh#L583)) and add a condition to ignore/delete the commoncap-symbol.patch for 4.14+ kernels.

**Comment by mavrothal** [comment]
fc994c8 should bypass this patch for 4.14+ kernels.
Unclear if the function of this patch, ie check execution security, is still needed in anyway.
